"""add_borrow_payment_state

Revision ID: ecd428f3f822
Revises: a1601601a892
Create Date: 2026-06-27 01:21:06.524555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd428f3f822'
down_revision: Union[str, Sequence[str], None] = 'a1601601a892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_record', sa.Column('borrow_payment_state', sa.String(length=50), nullable=True), schema='borrow_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_record', 'borrow_payment_state', schema='borrow_service')
    # ### end Alembic commands ###
